package com.maxello1.whamagic.magic;

public enum GlyphWarning {
    MISSING_RING,
    MISSING_CORE_SIGIL,
    UNRECOGNIZED_CORE_SIGIL,
    WEAK_RING,
    INVALID_SIGNS,
    AMBIGUOUS_INK,
    SUBSTANTIAL_UNKNOWN_INK,
    INCOMPLETE_RECOGNITION
}
